/*

	-TOZT-7 Napalm Unit
	
*/

Class MarFlamer_Ammo : Ammo
{
    Default
    {
		Inventory.PickupMessage "[Napalm Tank]";
		Inventory.Amount 210;
		Inventory.MaxAmount 630;
		Ammo.DropAmount 210;
		Ammo.BackpackAmount 210;
		Ammo.BackpackMaxAmount 630; //850
		Inventory.PickUpSound "Marathon/Items/Ammo";
		Inventory.Icon "";
	}
	States
    {
    Spawn:
		TZT7 Y -1;
		Stop;
	}
}

class MarFlamer_Group:MarathonDummy{
	states{
	spawn:
		TNT1 A 0 nodelay{
			let ammo=MarFlamer_Ammo(spawn("MarFlamer_Ammo",pos+(0,7,0),ALLOW_REPLACE));
			MarFuncs.TransferSpecials(self,ammo,MarFuncs.TS_ALL);
				spawn("MarFlamer_Ammo",pos+(0,-7,0),ALLOW_REPLACE);
			}stop;
		}
	}

class MarFlamethrower_Weapon : MarathonWeapon
{
    Default
    {
		ZWeapon.MagazineSize 210;
        Weapon.SelectionOrder 1000;
        Weapon.AmmoUse1 1;
        Weapon.AmmoGive1 210;
        Weapon.AmmoType1 "MarFlamer_Ammo";
		//Weapon.AmmoType2 "MarAssaultRifle_Grenades";
		Weapon.WeaponScaleX 1.25;
		Weapon.WeaponScaleY 1.25;
		
		Inventory.PickupMessage "( TOZT-7 Napalm Unit )";
		Tag "TOZT-7 Napalm Unit";
    }



    States
    {
    Ready:
		TZT7 A 0 A_JumpIf(invoker.ammocount>invoker.magazinesize, "Reload.Instant");
		TZT7 A 0 {A_Overlay(29,"RecoilShit");A_ClearOverlays(31,31);}
        TZT7 A 1 ZWL_WeaponReady(ZRF_NoPartialReload);
        Loop;

    Deselect:
		#### # 0 A_JumpIf(health <= 0, "Dead.Ass");
		TZT7 A 0 A_ClearOverlays(29,31);
        TZT7 A 1 A_Lower(3);
        Wait;
    Select:	
        TZT7 A 1 A_Raise(3);
        Wait;
	Noise.Maker:
		TNT1 A 3 A_StartSound("marathon/weapons/tozt7/fire",CHAN_WEAPON);
		loop;
    Fire:
		TZT7 B 0 A_JumpIf(waterlevel == 3, "Fire.Fail");
		TZT7 A 0 A_Overlay(31,"noise.maker");
	Flame:
        TZT7 B 0 A_JumpIf(waterlevel == 3, "Fire.Fail");
        TZT7 B 1
		{
			A_AlertMonsters(128);
			A_Recoil(0.05);
			//A_WeaponOffset(frandom(-2,2),frandom(31,33),WOF_INTERPOLATE);
			//ZWL_FireProjectile("MarFlame_Thrown_Kiwami",0,-1,angleOfs:frandom(-3,3),frandom(-3,3),flags:ZPF_AddPlayerVel);
			
			//Cosmetic
			//ZWL_FireProjectile("MarFlame_Thrown_Kiwami",0,-1,angleOfs:frandom(-3,3),frandom(-3,3),speed:frandom(40,45),0,flags:ZPF_AddPlayerVel|ZPF_DontUseAmmo);
			
			ZWL_FireProjectile("MarFlame_Thrown",0,-1,flags:ZPF_AddPlayerVel);
		}
		//look at this mess
		#### # 0 ZWL_JumpIfEmpty("Fire.End");
		#### A 0 ZWL_Refire("Flame");
	Fire.End:
		TZT7 A 1 A_ClearOverlays(31,31);
		Goto Ready;
	Fire.Fail:
		TZT7 A 8 A_ClearOverlays(31,31);
		Goto Ready;
	Reload:
		TZT7 # 0 A_ClearOverlays(31,31);
		TZT7 ## 1 A_Lower(1);
		TZT7 ####################### 1 A_Lower(3);
		TZT7 ## 1 A_Lower(1);
		TZT7 # 16;
		TZT7 # 16 ZWL_Reload();
		TZT7 ## 1 A_Raise(1);
		TZT7 ####################### 1 A_Raise(3);
		TZT7 ## 1 A_Raise(1);
		TZT7 A 0 ZWL_Refire("Fire");
		Goto Ready;
    Spawn:
        TZT7 Z -1;
        Stop;
    }
}

class MarFlame_Thrown : ZExplosive
{
    Default
    {
		Radius 8;
		Height 8;
		Speed 50;
		Scale 0.01;
		DamageFunction (frandom(8,12));
		DamageType "Fire";
		//Obituary "$OB_MPROCKET";
		renderstyle "add";
		alpha 0.1;
		
        +RollSprite
		+RollCenter
		-NoBlockMap
		+Ripper
		+NoBossRip
		+BloodlessImpact
		+ForceXYBillboard
		
		+BounceOnWalls
		+BounceOnFloors
		+BounceOnCeilings
		BounceCount 999;
        BounceFactor 0.1;
        WallBounceFactor 0.1;
    }

	States
	{
	Spawn:
		FX01 ABCDEFG 1 Bright A_SpawnItemEx("MarFlame_Sprites",flags:SXF_TRANSFERSPRITEFRAME);
		stop;
	Death:
		FX01 # 2 bright A_SpawnItemEx("MarFlame_Sprites",flags:SXF_TRANSFERSPRITEFRAME);
		stop;
	}
}

class MarFlame_Thrown_Kiwami : MarFlame_Thrown
{
	Default
	{
		Scale 0.85;
		alpha 1.0;
		RenderStyle "Add";
	}
	
		States
	{
	Spawn:
		FX01 ABCDEFG 1 Bright {A_FadeOut(0.1);A_SpawnItemEx("MarFlame_Sprites_Kiwami",flags:SXF_TRANSFERSPRITEFRAME);}
		stop;
	Death:
		FX01 # 2 bright A_FadeOut(0.5);
		wait;
	}
}

class MarFlame_Sprites : Actor
{
	Default
	{
		+DONTSPLASH;
		Radius 1;
		Height 1;
		Speed 5;
		+NoBlockmap;
		+NoGravity;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+RollSprite
		+RollCenter
		+DontBlast
		Alpha 0.1;
		Scale 0.85;
	}
	
		States
	{
	Spawn:
		#### # 1 bright nodelay; //A_FadeOut(-0.9);
		#### # 1 bright;
		stop;
	}
}

class MarFlame_Sprites_Kiwami : MarFlame_Sprites
{
	Default
	{
		Speed 25;
		RenderStyle "Add";
		Scale 0.85;
	}
	
		States
	{
	Spawn:
		#### # 1 bright A_FadeOut(0.3);
		wait;
	}
}